server:  
    port: 7000
    #address: localhost
    context-path: /
# DATASOURCE
spring:
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
    datasource: 
        name: db_jxc
        url: jdbc:mysql://106.14.135.185:3306/gms_new?characterEncoding=UTF-8
        username: root
        password: Ryonwhl1314?
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        #cachePrepStmts: true 开启二级缓存
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
nikehomedir: E://test//imagePath//
quickhomedir: E://test//quickMark//
image: 
    server: 
        hostaddress: http://localhost/static/
        headShot: headshot/
        goodsPic: goodspic/
        shopMark: shopMark/
        couponMark: couponMark/
        customerMark: customerMark/
        realMark: realMark/
    quickmark:
        rows: 13
        cols: 41
        modelSize: 2
        qzsize: 1
        type: .png