server:  
    port: 7000
spring: 
    jpa:
        hibernate.ddl-auto: update
        show-sql: true
    datasource: 
        name: db_jxc
        url: jdbc:mysql://localhost:3306/gms_new?characterEncoding=UTF-8
        username: root
        password: root 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat,log4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        #cachePrepStmts: true 开启二级缓存
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        suffix: .html
        template-loader-path: classpath:/templates/
        request-context-attribute: request
picuploadPath: //src//main//resources//static//imagePath//
quickuploadPath: //src//main//resources//static//quickMark//shopMark//
couponuploadPath: //src//main//resources//static//quickMark//couponMark//
customeruploadPath: //src//main//resources//static//quickMark//customerMark//
image: 
    server: 
        sourcePath: /static/imagePath/
        shopMark: /static/quickMark/shopMark/
        couponMark: /static/couponMark/couponMark/
        customerMark: /static/customerMark/customerMark/
    quickmark:
        rows: 25
        cols: 25
        modelSize: 5
        qzsize: 16
        type: .png